Repository mgamlem3/Energy-Dashboard, pull requests merged in 2019-04, with the labels that each got.

#61 Upgrade outdated packages
  yarn.lock
Labels: enhancement

#62 Make important structural changes to prepare for database
  package.json
  src/building_comparison.js
  src/building_details.js
  src/components/App/App.jsx
  src/components/BuildingDetails/buildingDetails.jsx
  src/components/BuildingList/buildingList.jsx
  src/components/Header/header.jsx
  src/index.js
Labels: Backend, Data, priority-high

#71 Add database
  .babelrc
  .eslintignore
  .gitignore
  package.json
  src/components/App/App.jsx
  src/database functions/api_functions.mjs
  src/server/data.js
  src/server/package.json
  src/server/server.js
  src/server/yarn.lock
  yarn.lock
Labels: Backend, Data, question

#73 Tristan
  src/building_details.js
  src/components/DetailspageContent/detailspage-content.jsx
  src/components/DetailspageContent/styles.js
  src/components/Graphs/LineGraph/line-graph.jsx
Labels: Data, Graph

#92 Update README to include Data Repo
  README.md
Labels: priority-low

#88 Tristan
  package.json
  src/building_comparison.js
  src/components/App/App.jsx
  src/components/BuildingList/buildingList.jsx
  src/components/ComparisonpageContent/comparisonpage-content.jsx
  src/components/ComparisonpageContent/styles.js
  src/components/DetailspageContent/detailspage-content.jsx
  src/components/Graphs/LineGraph/line-graph.jsx
  src/components/Graphs/MixGraph/mix-graph.jsx
  src/components/Graphs/PieGraph/pie-graph.jsx
  src/database functions/api_functions.mjs
  src/server/data.js
  src/server/package.json
  src/server/server.js
  webpack.config.js
  yarn.lock
Labels: Graph

#98 End of Sprint 2
  .babelrc
  .eslintignore
  .gitignore
  README.md
  package.json
  src/building_comparison.js
  src/building_details.js
  src/components/App/App.jsx
  src/components/BuildingDetails/buildingDetails.jsx
  src/components/BuildingList/buildingList.jsx
  src/components/BuildingList/styles.js
  src/components/CampusMap/campusmap.jsx
  src/components/CampusMap/styles.js
  src/components/ComparisonpageContent/comparisonpage-content.jsx
  src/components/ComparisonpageContent/styles.js
  src/components/DetailspageContent/detailspage-content.jsx
  src/components/DetailspageContent/styles.js
  src/components/DisplaySidebar/display-sidebar.jsx
  src/components/DisplaySidebar/styles.js
  src/components/Graphs/LineGraph/line-graph.jsx
  src/components/Graphs/MixGraph/mix-graph.jsx
  src/components/Graphs/PieGraph/pie-graph.jsx
  src/components/Header/header.jsx
  src/components/HomepageContent/homepage-content.jsx
  src/components/HomepageContent/styles.js
  src/components/Logo/logo.jsx
  src/components/Logo/styles.js
  src/components/ManagementDetails/management-details.jsx
  src/components/ManagementDetails/styles.js
  src/components/ManagementSidebar/management-sidebar.jsx
  src/components/ManagementSidebar/styles.js
  src/components/Nav/nav.jsx
  src/components/Nav/styles.js
  src/database functions/api_functions.mjs
  src/display.html
  src/display.js
  src/index.js
  src/management.html
  src/management.js
  src/server/data.js
  src/server/package.json
  src/server/server.js
  src/server/yarn.lock
  webpack.config.js
  yarn.lock
Labels: enhancement

#100 Change Building Strings to Common Resource Objects
  src/components/BuildingDetails/buildingDetails.jsx
  src/components/BuildingList/buildingList.jsx
  src/components/BuildingList/styles.js
  src/database functions/api_functions.mjs
  src/resources/common-text-resources.js
Labels: Backend, enhancement

#119 Fix No-SQL Injection Bug
  src/server/package.json
  src/server/server.js
  src/server/yarn.lock
Labels: bug, priority-high

#126 Update Database Functions
  .eslintrc.json
  package.json
  src/components/App/App.jsx
  src/components/DetailspageContent/detailspage-content.jsx
  src/database functions/api_functions.js
  src/server/data.js
  src/server/package.json
  src/server/process_data.js
  src/server/server.js
Labels: Backend, Data, bug

#128 License Application and Server under MIT
  LICENSE
  package.json
  src/server/LICENSE
  src/server/package.json
Labels: question

#130 Add function to get averages from database
  src/database functions/api_functions.js
Labels: Backend, Data

#140 Fix bugs related to date parse and add favicon
  .gitignore
  package.json
  src/components/SignIn/sign_in.jsx
  src/components/SignIn/styles.js
  src/database functions/api_functions.js
  src/resources/favicon.ico
  src/server/server.js
  yarn.lock
Labels: Backend

#141 Update Sign in Component to use Firebase auth
  src/components/SignIn/sign_in.jsx
  src/sign_in.html
Labels: Backend, Management Page

#135 Add ability to get main graph data
  src/database functions/api_functions.js
  src/server/MainGraphDataReturn.js
  src/server/constants.js
  src/server/process_data.js
  src/server/server.js
Labels: Backend, Data, Graph
